name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v3
      with:
        name: openvpn-plugin-auth-script
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "openvpn-plugin-auth-script.linux-amd64.tar.gz,sha256sum.txt"
        bodyFile: CHANGELOG.md
        allowUpdates: true
        removeArtifacts: true
